/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.awt.Dimension;

import controller.ControllerArvore;
import gui.java2d.ComponentArvore2D;

/**
 *
 * @author gustavo
 */
public class TelaBuscaArvore extends javax.swing.JFrame {
	
	private ControllerArvore controller;
	private ComponentArvore2D arvore2D;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaBuscaArvore() {
    	controller = ControllerArvore.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        removeNodeButton = new javax.swing.JButton();
        alterarNodeButton = new javax.swing.JButton();
        buscaProfButton = new javax.swing.JButton();
        buscaLargButton = new javax.swing.JButton();
        addNodeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca em árvore");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(220, 220, 220));
        setPreferredSize(new java.awt.Dimension(750, 500));

        jPanel1.setLayout(new BorderLayout());
        jPanel1.setPreferredSize(new Dimension(750, 400));
        arvore2D = new ComponentArvore2D(controller.getArvore());
        jPanel1.add(arvore2D, BorderLayout.NORTH);
        jPanel1.setVisible(true);

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 100));

        removeNodeButton.setText("Remover Nó");
        removeNodeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeNodeButtonMouseClicked(evt);
            }
        });

        alterarNodeButton.setText("Alterar Nó");
        alterarNodeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	alterarNodeButtonMouseClicked(evt);
            }
        });

        buscaProfButton.setText("Busca em profundidade");
        buscaProfButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	buscaProfButtonMouseClicked(evt);
            }
        });

        buscaLargButton.setText("Busca em largura");
        buscaLargButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	buscaLargButtonMouseClicked(evt);
            }
        });

        addNodeButton.setText("Adicionar Nó");
        addNodeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	addNodeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNodeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeNodeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alterarNodeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscaProfButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscaLargButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeNodeButton)
                    .addComponent(alterarNodeButton)
                    .addComponent(buscaProfButton)
                    .addComponent(buscaLargButton)
                    .addComponent(addNodeButton)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNodeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNodeButtonMouseClicked
        (new TelaAddNode(this, true)).setVisible(true);
    }//GEN-LAST:event_addNodeButtonMouseClicked

    private void removeNodeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNodeButtonMouseClicked
    	(new TelaRemoverNode(this, true)).setVisible(true);
    }//GEN-LAST:event_addNodeButtonMouseClicked

    private void alterarNodeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNodeButtonMouseClicked
    	(new TelaSelecionarNodeAlteracao(this, true)).setVisible(true);
    }//GEN-LAST:event_addNodeButtonMouseClicked

    private void buscaProfButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNodeButtonMouseClicked
    	(new TelaSelecionarNodeBusca(this, true, TelaSelecionarNodeBusca.PROFUNDIDADE)).setVisible(true);
    }//GEN-LAST:event_addNodeButtonMouseClicked

    private void buscaLargButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNodeButtonMouseClicked
    	(new TelaSelecionarNodeBusca(this, true, TelaSelecionarNodeBusca.LARGURA)).setVisible(true);
    }//GEN-LAST:event_addNodeButtonMouseClicked
    
    @Override
    public void repaint() {
    	super.repaint();
    	arvore2D.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNodeButton;
    private javax.swing.JButton alterarNodeButton;
    private javax.swing.JButton buscaLargButton;
    private javax.swing.JButton buscaProfButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton removeNodeButton;
    // End of variables declaration//GEN-END:variables
}
