/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import controller.Controller;
import model.Node;

/**
 *
 * @author gustavo
 */
public class TelaSelecionarNodeBusca extends javax.swing.JDialog {

    public static final int PROFUNDIDADE = 0;
	public static final int LARGURA = 1;
	
	private Controller controller;
    private int tipoBusca;

    /**
     * Creates new form AddNode
     */
    public TelaSelecionarNodeBusca(java.awt.Frame parent, boolean modal, int tipoBusca) {
        super(parent, modal);
        this.tipoBusca = tipoBusca;
        this.controller = controller.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nomeNode = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar nó - " + getNomeBusca());

        jLabel2.setText("Nó:");

        nomeNode.setModel(new javax.swing.DefaultComboBoxModel<>());
        ArrayList<Node> listaNodes = controller.getListaNodes();
        for (Node node : listaNodes) {
			nomeNode.addItem(node.getNome());
		}

        cancelButton.setText("Cancelar");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });

        okButton.setText("OK");
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(18, 18, 18)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(nomeNode, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        int custoBusca = -1;
        String nomeNo = (String) nomeNode.getSelectedItem();
    	if(tipoBusca == LARGURA)
        	custoBusca = controller.buscaLargura(nomeNo);
    	else
    		custoBusca = controller.buscaProfundidade(nomeNo);
    	JOptionPane.showMessageDialog(this, "Custo para procurar o no "+nomeNo+", usando busca em "+getNomeBusca()+": "+custoBusca,
    									"Busca em "+getNomeBusca(), JOptionPane.PLAIN_MESSAGE);
    	this.dispose();
    }//GEN-LAST:event_okButtonMouseClicked

    private String getNomeBusca() {
    	String nomeBusca;
        if(tipoBusca == PROFUNDIDADE)
        	nomeBusca = "Profundidade";
        else
        	nomeBusca = "Largura";
		return nomeBusca;
	}

	private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> nomeNode;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
